### PR TITLE
Expose getMatchingSchemas

### PR DESCRIPTION
**Pull request by ianchi**
Expose a new method `getMatchingSchemas` that resolves the applicable schema for the document and return the matching schema for each document node.

This is very useful for extending the functionality of the validator and adding custom keys.

I need to do some custom validation and exposing this simple function would make it super easy to implement.
Otherwise I'd need to duplicate a lot of code.

### CODE REVIEW

**Comment by ianchi** [comment]
Fixed error when no schema matches.
Additionally export some members for `jsonDocument`.
They are also needed to easily extend functionality.

**Comment by aeschli** [comment]
@ianchi I'm very hesitant to make `getMatchingSchemas` API in the current form. 
Can you provide some use cases?

**Comment by ianchi** [comment]
Hi @aeschi,

I have a schema that has a custom keyword that triggers a custom validation logic.
I need to do this validation on the input files and report errors on a cli tool and also I made an extension that adds the errors as diagnostics to VSCode.

Having the matching schemas makes all this dead simple.
Without that I would have to rewrite all the schema validation logic, as there is no extension mechanism.

This can be validated with custom keywords using Ajv, but it is really not useful for reporting document position of the error.

I understand that it exposes some implementation details, but it allows to use it to easily extend functionality.
Alternatively some hook could be implemented to call custom functions, but I understood from some other Issue, that you weren’t willing to do so.

Exposing some of jsonDocument functionality also allows me to easily add some custom hover info with the vscode extension, that is dependant on the schema of the cursor’s node

**Comment by ianchi** [comment]
Hi @aeschli, any chance of considering this?

Or any other approach to leverage this service and be able to extend it to use it on custom validations an hoover info?

**Comment by aeschli** [comment]
Hi @ianchi , I pushed a commit that hides the inverted schema. Also I polished the code and added tests.

If you can sign the CLA, then I can push the change.

**Comment by ianchi** [comment]
Hi @aeschli,
Just signed the CLA.
Great to see this merged.

Thanks!

**Pull request merged**
