### PR TITLE
Don't wrap in array and object completions

### PR DESCRIPTION
**Pull request by FloEdelmann**
Closes https://github.com/Microsoft/vscode/issues/50528

### CODE REVIEW

**Comment by aeschli** [comment]
@FloEdelmann Please update the tests as well.

**Comment by FloEdelmann** [comment]
@aeschli The tests (and another place where the same completions are suggested) are now fixed.

Unfortunately, the Travis CI tests still fail. Am I right that that is not related to my changes?

**Comment by FloEdelmann** [comment]
@aeschli Any updates on this? Is it possible that this will make it into the October Release?

**Comment by aeschli** [comment]
merged, thanks!

**Comment by FloEdelmann** [comment]
Nice, thank you!

**Pull request merged**
