### PR TITLE
Use 'if' to create completions

### PR DESCRIPTION
**Pull request by Levertion**
I'm not certain that this implementation is correct for the codebase, but it doesn't break any of the other tests (as added in #24) and passes my new test. @fer0x: if you could validate that this looks right too.

I've only added one test case, but want to check that this feature is desired before adding more tests.

### CODE REVIEW

**Comment by Fer0x** [comment]
@Levertion works correct for me. Thanks for enhancement.

**Comment by aeschli** [comment]
@Levertion The test is still failing...

**Comment by Levertion** [comment]
OK - I've written enough tests to convince me that my behaviour is correct, although I'm unsure about the formatting.

Should we format automatically somehow - clearly the style is to use `'`, but my personal habit is to use `"` so that is what I have used. I would expect there to be automatic formatting, but the builtin `vscode` formatting changes the style of the rest of the file, `prettier` is not being used and the `tslint` rules used does not control formatting.

My personal preference is [`prettier`](https://prettier.io/), but if the current formatting needs manually editing, let me know.

**Comment by aeschli** [comment]
just use the built-in TypeScript formatter with default settings

**Comment by Levertion** [comment]
I have tried that, using both format document and format selection after commenting out my entire `settings.json` and disabling all extensions for the workspace. This however led to only the minimal diff seen in 9f3ac837755d0a8b5aacd0552164b4932a246333, which doesn't seem optimal. Is that enough?

**Comment by aeschli** [comment]
Yes, that's fine. The formatter preserves new lines, that's why the changes are so small.

**Comment by aeschli** [comment]
It's great, thanks a lot @Levertion !

**Pull request merged**
